-- Specs for the in-repo fixtures. Run with:
--   botster-plugin-test --plugin fixtures specs/kit_fixture_spec.lua
local kit = require("botster.test")

kit.test("a tool call runs the real handler and writes plugin_db", function(t)
  local p = t:load("kit-fixture")
  local stored = p:call_tool("kit-fixture.remember", { key = "alpha", value = "one" })
  t:eq(stored.ok, true)
  t:eq(stored.result.stored, "alpha")
  t:eq(p:db_get("alpha").value, "one")
  t:match(p:logs(), { { level = "info", message = "remembered" } })
end)

kit.test("an emitted event reaches the downstream handler inside the step", function(t)
  local p = t:load("kit-fixture")
  t:eq(p:call_tool("kit-fixture.note", { key = "beta" }).result.emitted, true)
  t:eq(p:db_get("noted").items[1], "beta")
  t:match(p:emitted_events(), { { owner = "kit-fixture", name = "kit-fixture.noted", payload = { key = "beta" } } })
end)

kit.test("session input reaches the plugin as production frames", function(t)
  local p = t:load("kit-fixture")
  t:sessions_baseline({ kit.session({ id = "sess-a", state = "running" }) })
  t:session_upsert(kit.session({ id = "sess-a", state = "exited", code = 0 }))
  t:session_remove("sess-a")
  local family = p:db_get("family").items
  t:eq(#family, 5)
  t:eq(family[4].lifecycle_class, "ended")
  t:eq(family[5].type, "entity_remove")
end)

kit.test("a plugin that calls the removed events.on fails to load", function(t)
  local plugin, err = t:try_load("removed-events-on")
  t:eq(plugin, nil)
  t:ok(err ~= nil, "a load error is reported")
  t:ok(tostring(err.message):find("events", 1, true), err.message)
end)

kit.test("a timer armed after advance fires one delay later", function(t)
  local p = t:load("kit-fixture-timer")
  t:eq(#t:advance(5000), 0)
  t:eq(p:call_tool("kit-fixture-timer.arm", { delay_ms = 1000 }).ok, true)
  t:eq(#t:advance(999), 0)
  local fired = t:advance(1)
  t:eq(#fired, 1)
  t:eq(fired[1].package, "kit-fixture-timer")
end)

kit.test("unsupported features refuse with the gate", function(t)
  local p = t:load("kit-fixture")
  local refused = p:call_tool("kit-fixture.read", { key = "x" }, { token = "raw-credential" })
  t:eq(refused.ok, false)
  t:eq(refused.error.kind, "unsupported_by_kit")
  t:eq(refused.error.gate, "G1")
  t:eq(pcall(function() return p:views() end), false)
end)

kit.test("a routed envelope is received again until the target acknowledges it", function(t)
  local p = t:load("kit-fixture")
  p:call_tool("kit-fixture.route", {
    envelope_id = "env-1",
    target = { type = "session", session_id = "sess-b" },
    body = "hello",
  })
  t:eq(#p:routed("sess-b"), 1)
  t:eq(p:routed("sess-b")[1].payload.body, "hello")
  t:eq(#t:receive_routed("sess-b"), 1)
  t:eq(#t:receive_routed("sess-b"), 1)
  t:ok(t:ack_routed("sess-b", "env-1"))
  t:eq(#t:receive_routed("sess-b"), 0)
end)

kit.test("a Hub request table goes through the production path", function(t)
  local response = t:request({ type = "plugin_mcp_list_tools" })
  t:eq(response.ok, true)
end)

kit.test("published entities reach a client subscription as flat frames", function(t)
  local p = t:load("kit-fixture")
  t:eq(#p:entities("kit-fixture.item"), 1, "the first read subscribes and gets the snapshot")
  t:eq(p:call_tool("kit-fixture.publish", { id = "a", label = "First" }).ok, true)
  local frames = p:entities("kit-fixture.item")
  t:eq(frames[#frames].type, "entity_upsert")
  t:eq(frames[#frames].id, "a")
  t:match(frames[#frames].entity, { label = "First" })
end)

kit.test("a refused entity subscription raises and is retried, never an empty read", function(t)
  local p = t:load("kit-fixture")
  for attempt = 1, 2 do
    local ok, err = pcall(function() return p:entities("no.such.type") end)
    t:eq(ok, false, "attempt " .. attempt .. " raises")
    t:ok(tostring(err):find("entity_provider_unavailable", 1, true), tostring(err))
  end
end)

kit.test("distinct large integers are unequal for eq and match", function(t)
  local low, high = 9007199254740992, 9007199254740993
  t:eq(pcall(function() t:eq(low, high) end), false)
  t:eq(pcall(function() t:match(low, high) end), false)
  t:eq(pcall(function() t:eq({ n = { low } }, { n = { high } }) end), false)
  t:eq(pcall(function() t:match({ n = { low } }, { n = { high } }) end), false)
  t:eq(pcall(function() t:eq(low, low) end), true)
end)

kit.test("a consumer that loads before its producer receives the producer's events", function(t)
  local consumer = t:load("kit-fixture-consumer") -- subscribes to kit-fixture; kit-fixture is not loaded yet
  local producer = t:load("kit-fixture")
  t:eq(producer:call_tool("kit-fixture.note", { key = "late" }).result.emitted, true)
  t:eq(consumer:call_tool("kit-fixture-consumer.seen", {}).result.items[1], "late")
end)

kit.test("a tool runs for the caller the Hub set", function(t)
  local p = t:load("kit-fixture")
  t:eq(p:call_tool("kit-fixture.whoami", {}).result.caller.kind, "operator")
  local as_a = p:call_tool("kit-fixture.whoami", {}, { caller = { session_id = "sess-a" } })
  t:eq(as_a.ok, true)
  t:eq(as_a.result.caller.kind, "session")
  t:eq(as_a.result.caller.session_id, "sess-a")
  t:ok(as_a.result.caller.hub_id ~= nil, "the hub id defaults to the kit Hub's own")
  t:eq(p:call_tool("kit-fixture.whoami", {}, { caller = { kind = "operator" } }).result.caller.kind, "operator")
  t:eq(p:call_tool("kit-fixture.whoami", {}).result.caller.kind, "operator", "the caller is for one call")
  t:eq(pcall(function() return p:call_tool("kit-fixture.whoami", {}, { caller = { kind = "bogus" } }) end), false)
end)

kit.test("the strict-globals check finds an undefined global that no call reaches", function(t)
  local clean = t:load("kit-fixture")
  t:eq(#clean:undefined_globals(), 0)
  local bad = t:load("kit-fixture-badglobal")
  t:eq(bad:call_tool("kit-fixture-badglobal.noop", {}).result.ok, true, "the runtime path passes")
  local found = bad:undefined_globals()
  t:eq(#found, 1)
  t:match(found[1], { file = "plugin.lua", name = "log", line = 5, write = false })
end)
